### ISSUE TITLE
Appsettings in Specflow.json

### ISSUE THREAD

**Issue by akashmehta-gep** [techtalk/SpecFlow-Examples#26]
Is there a way to set AppSettings in specflow.json? So I can retrieve it later from ConfigurationManager?

**Comment by SabotageAndi** [comment]
No, there isn't.
specflow.json is only the configuration for SpecFlow itself.

**Comment by akashmehta-gep** [comment]
Thanks for the reply! I'm using SpecFlow 3.0.132-beta version. Any idea how one can store key value pairs in Specflow.json and retrieve it via ConfigurationManager like one can using App.config?

**Comment by SabotageAndi** [comment]
That depends completely on the used .NET Framework. in .NET 4.* you have still the app.config. In .NET Core I am not sure if it still exists. There are other ways now (https://msdn.microsoft.com/en-us/magazine/mt632279.aspx?f=255&MSPPError=-2147217396, https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1)

These are not SpecFlow specific. This is general .NET Framework/.NET Core stuff.

**Comment by akashmehta-gep** [comment]
Because I wanted to generate SpecRun HTML reports. The project I'm working on is in .NET core and I'm using the latest Beta build
