### ISSUE TITLE
New Specflow version makes "@ignore" tag stop working

### ISSUE THREAD

**Issue by anapsousa** [techtalk/SpecFlow-Examples#7]
Hi, I just updated to this latest version of specflow and my "@ignore" tags stopped working. Is there anything that affects the behavior of the tags being changed in this particular version? 
I get " There is no argument given that corresponds to the required formal parameter 'reason' of 'IgnoreAttribute.IgnoreAttribute(string)' ". 
Can someone please help with this issue? 
Thanks in advance.

**Comment by Akanshi07** [comment]
m getting the same error please help

**Comment by SabotageAndi** [comment]
@anapsousa & @Akanshi07 this is the wrong repo for this issue. In this repo are only the examples for SpecFlow.

Please use the issue tracker here: https://github.com/techtalk/SpecFlow/issues

**Comment by anapsousa** [comment]
Thank you @SabotageAndi 
I'll put it there

**Comment by SabotageAndi** [comment]
Thanks!
